name: JAVA CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  block-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run shell script
        run: |
          sh check_for_merge.sh
      - name: Check exit code
        run: |
          if [ $? -ne 0 ]; then
            echo "Error: tests failed"
            exit 1
          fi
